In [2]:
import numpy as np

In [9]:
a = np.arange(12).reshape((3,4))
b = np.arange(3)
a, b, a.T * b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([0, 1, 2]),
 array([[ 0,  4, 16],
        [ 0,  5, 18],
        [ 0,  6, 20],
        [ 0,  7, 22]]))